name: Build and Archive node_modules

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Archive node_modules
        run: zip -r nodemod.zip node_modules
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: nodemod.zip
